/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class luofeng_com_ffmpegdemo_FFmpegUtils */

#ifndef _Included_luofeng_com_ffmpegdemo_FFmpegUtils
#define _Included_luofeng_com_ffmpegdemo_FFmpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     luofeng_com_ffmpegdemo_FFmpegUtils
 * Method:    getFFmpegInfo1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luofeng_com_ffmpegdemo_FFmpegUtils_getFFmpegInfo1
  (JNIEnv *, jobject);

/*
 * Class:     luofeng_com_ffmpegdemo_FFmpegUtils
 * Method:    getFFmpegInfo2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luofeng_com_ffmpegdemo_FFmpegUtils_getFFmpegInfo2
  (JNIEnv *, jobject);

/*
 * Class:     luofeng_com_ffmpegdemo_FFmpegUtils
 * Method:    getFFmpegInfo3
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luofeng_com_ffmpegdemo_FFmpegUtils_getFFmpegInfo3
  (JNIEnv *, jobject);

/*
 * Class:     luofeng_com_ffmpegdemo_FFmpegUtils
 * Method:    getFFmpegInfo4
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luofeng_com_ffmpegdemo_FFmpegUtils_getFFmpegInfo4
  (JNIEnv *, jobject);

/*
 * Class:     luofeng_com_ffmpegdemo_FFmpegUtils
 * Method:    getFFmpegInfo5
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luofeng_com_ffmpegdemo_FFmpegUtils_getFFmpegInfo5
  (JNIEnv *, jobject);

/*
 * Class:     luofeng_com_ffmpegdemo_FFmpegUtils
 * Method:    getFFmpegInfo6
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_luofeng_com_ffmpegdemo_FFmpegUtils_getFFmpegInfo6
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
